apiVersion: v1
kind: PersistentVolume
metadata:
        name: pvvol-1
spec:
        capacity:
                storage: 1Gi
        accessModes:
                - ReadWriteMany
        persistentVolumeReclaimPolicy: Recycle
        nfs:
                path: /var/sfw
                server: cp01
                readOnly: false
