---
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: readiness
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    readinessProbe:
      httpGet:
        path: /
        port: 80
      #Wait for 5 seonds after container is created
      initialDelaySeconds: 5
      #Check every 5 seconds time period
      periodSeconds: 5
...
