---
apiVersion: v1
kind: Pod
metadata:
  name: always-policy-pod
spec:
  #This is already the default
  restartPolicy: Always
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'sleep 10']
...
