---
apiVersion: v1
kind: Pod
metadata:
  name: onfailuer-policy-pod
spec:
  #only restarts if failed
  restartPolicy: OnFailure
  containers:
  - name: busybox
    image: busybox
    #According to this failed command, the pod will be recreated every time and number of Restarts in k get pods will increase for this pod
    command: ['sh', '-c', 'sleep 10; OMG I'm a bad command that will cause the container to fail!']
...
