#kubectl create secret generic nginx-htpasswd --from-file .htpasswd
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.19.1  
    ports:
    - containerPort: 80
    volumeMounts:
    - name: config-volume
      mountPath: /etc/nginx
    - name: secret-volume
      mountPath: /etc/nginx/conf
  volumes:
  - name: config-volume
    configMap:
      name: nginx-config # Name of the configMap resource in the k8s-namespace
  - name: secret-volume
    secret:
      secretName: nginx-htpasswd  # Name of the secret resource in the k8s-namespace
