apiVersion: v1
kind: Pod
metadata:
        name: cmpod-demo
spec:
        containers:
                - name: cmpod-demo-cont
                  image: nginx
                  # here it goes
                  #env:
                          #- name: ilike
                          #valueFrom:
                          #configMapKeyRef:
                          #name: colors
                          #key: favorite
                  #envFrom:
                  #- configMapRef:
                  #name: colors
                  volumeMounts:
                          - name: car-vol
                            mountPath: /etc/cars
        volumes:
                - name: car-vol
                  configMap:
                          name: fast-car
