apiVersion: v1
kind: PersistentVolume
metadata:
        name: 5gpv01
        labels:
                type: local
spec:
        capacity:
                storage: 5Gi
        accessModes:
                - ReadWriteOnce
        hostPath:
                path: "/var/data01"
