apiVersion: v1
kind: Pod
metadata:
  name: my-multi-pod
spec:
  volumes:
  - name: shared-vol
    emptyDir: {}
  containers:
  - name: main-cont1  
    image: busybox
    command: ['sh', '-c', 'while true; do echo SUCCESS! >> /store/output.log; sleep 5 ; done']
    volumeMounts:
    - name: shared-vol
      mountPath: /store
  - name: log-cont1
    image: busybox
    command: ['sh', '-c', 'while true; do cat /log/output.log; sleep 5 ; done']
    volumeMounts:
    - name: shared-vol
      mountPath: /log
